// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpVMHRG9Xu8mLmjXo6mLsutniXPN2yGrs',
    appId: '1:265049171088:web:3d6facbe3da8ede95ae415',
    messagingSenderId: '265049171088',
    projectId: 'appinio-restaurant-1000a',
    authDomain: 'appinio-restaurant-1000a.firebaseapp.com',
    storageBucket: 'appinio-restaurant-1000a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJAhHcffX0OEMTESaNrwCZfJk3WzceFVo',
    appId: '1:265049171088:android:37adb09a4a7cc45d5ae415',
    messagingSenderId: '265049171088',
    projectId: 'appinio-restaurant-1000a',
    storageBucket: 'appinio-restaurant-1000a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAktJbmf8jrg-ebte_WoD8XXwN068DE9s4',
    appId: '1:265049171088:ios:01dde9dcceb376da5ae415',
    messagingSenderId: '265049171088',
    projectId: 'appinio-restaurant-1000a',
    storageBucket: 'appinio-restaurant-1000a.appspot.com',
    iosClientId: '265049171088-cq74sjnl9g440hpiba3rbq0h88uvsipv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appinioRestaurant',
  );
}
